### ISSUE TITLE
moving ticket gen code to 3ds

### ISSUE THREAD

**Issue by Sazoji** [HouseBreaker/Shameless#1]
suggestion: moving ticket generation code (titles on tik files is game changing ) to a 3ds app for fbi code installation of cdn content without title scrolling/ ciangel crappy search

**Comment by HouseBreaker** [comment]
The reason I made this program in the first place is so I could access the database from the comfort of my PC's keyboard. Making the same program for 3DS would be redundant. Especially since other apps exist which do this on the 3DS.
