### ISSUE TITLE
Generate All Tickets feature doesn't output any files

### ISSUE THREAD

**Issue by Jaitsu** [HouseBreaker/Shameless#10]
Using the latest version, 1.8.6, clicking the Generate All Tickets button and pointing it at a directory causes it to supposedly generate the tickets, with the progress bar moving and all, but after it's done there are no files in the destination directory. I've even tried pre-creating the tickets folder and running it as administrator; no dice. Everything else works as expected with the QR code generator functions.

**Comment by HouseBreaker** [comment]
I honestly don't know, ticket generation works fine over here and all the code for writing tickets to files should fail if it couldn't write to the directory.

**Comment by Jaitsu** [comment]
Oh, I figured out what it is. It's ignoring the location chosen in the file browser, and always creating/populating the tickets folder in its own directory (./tickets), even though the success window says they were generated where I directed it.
