### ISSUE TITLE
1.8.7 incorrect archive format

### ISSUE THREAD

**Issue by sharrken** [HouseBreaker/Shameless#12]
The Shameless_1.8.7.zip won't open with Explorer's built in zip extraction as it is 'corrupt/invalid'. 7zip throws an error but realises that it's actually a `.rar` file and extracts the contents fine. Just thought I'd let you know.
![explorer error](https://cloud.githubusercontent.com/assets/19295335/15444418/4cbe1758-1ee8-11e6-883d-c16c1fa61ba7.PNG)
![7z error](https://cloud.githubusercontent.com/assets/19295335/15444419/4f87db5e-1ee8-11e6-8417-16f3bbc9c523.PNG)

**Comment by HouseBreaker** [comment]
oh jesus, I wrote myself a little automating script so I wouldn't have to make an archive myself and rename it to upload to github and I guess I messed up with the archiving part...

**Comment by HouseBreaker** [comment]
The release is updated. Thank you.
