### ISSUE TITLE
Error when almost done downloading

### ISSUE THREAD

**Issue by JMartJonesy** [HouseBreaker/Shameless#13]
I just recently installed a9lh and have started download some games. I was able to download Pokemon X just fine but get an error whenever I try to install anything else, this usually occurs when I am almost done downloading the games. The only thing I have noticed is that the region for Pokemon says all while the other games I have been downloading the USA version. I have already made sure my 3ds's region is set to USA. Any suggestions?

**Comment by HouseBreaker** [comment]
What cfw are you running?

**Comment by JMartJonesy** [comment]
I just installed a9lh with luma3ds

**Comment by HouseBreaker** [comment]
Do you have region free enabled in luma3ds' settings?

Also, try installing some game and get the error code at the end if you can. It will help in figuring out what the problem is.

**Comment by JMartJonesy** [comment]
Ill try getting the error code again and post it. I have not changed any of the luma3ds settings, Ill see if that is the issue also

**Comment by JMartJonesy** [comment]
I went into luma3ds and checked the region settings but am still getting errors.
The error message I am getting is 

Failed to Install: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argumet (7)
Module: AM(32)
Desc: Cert signature or hash check failed (106)

**Comment by HouseBreaker** [comment]
Something's up with the signature checks I guess... I'm not sure. At this point it's a problem with the actual FBI installation, Shameless has done its job at providing you with a link and QR code to the ticket.

**Comment by JMartJonesy** [comment]
Its seems unusual that I was able to install pokemon just fine but the rest aren't working I have to post on /r/3dshacks

**Comment by HouseBreaker** [comment]
Actually, at this point I'm pretty sure the ticket is actually installed. Try going into the eShop page of the title and clicking "redownload". It should get redownloaded properly, even if FBI can't download it.

**Comment by JMartJonesy** [comment]
I actually tried that also and it fails near the end as well

**Comment by HouseBreaker** [comment]
Yeah, something's probably up with your cfw and it's messing w/ the signature checks. Since it can't even redownload a title...

**Comment by HouseBreaker** [comment]
Either that or Nintendo finally got smart and started actually checking whether you own the game before downloading it.

**Comment by JMartJonesy** [comment]
hmm why would it work for Pokemon though if that was the case?

**Comment by HouseBreaker** [comment]
I'm not sure. Try something like 2048, which is available for all regions and is small enough to install quickly.

**Comment by JMartJonesy** [comment]
Just download super metroid which is all and it worked fine so it must be a region thing then
