### ISSUE TITLE
Feature Request: Show differences between current database and latest update when a update is avaliable

### ISSUE THREAD

**Issue by Masamune3210** [HouseBreaker/Shameless#15]
Maybe highlight the differences after the update completes. Would make it easier to see what has been added

**Comment by HouseBreaker** [comment]
But you get the difference when the titles update.

Best I can do is a show more info button or something which lists all titles if you want.

**Comment by Masamune3210** [comment]
Unless I'm missing something, you only get a small list which doesnt include all the changes.
It would be awesome if you could add the button, maybe a seperate screen or just sort the list to have the titles sorted by date added
