### ISSUE TITLE
Install Ticket Without CFW?

### ISSUE THREAD

**Issue by rpalmon** [HouseBreaker/Shameless#19]
Is there a homebrew application that I can use to install the ticket without a CFW? Please link it to me if there is one.

**Comment by Committee** [comment]
Only LEGIT CIA's can be installed without CFW and for <11.0 firmware

**Comment by rpalmon** [comment]
That doesn't really ask my question. I am asking if you could install a ticket without a CFW. (I am FW 11.0)

**Comment by HouseBreaker** [comment]
no. you need to modify the internal memory to inject tickets and you need kernel access to modify the internal memory.

**Comment by rpalmon** [comment]
How could I modify the internal memory, do I need CFW?

**Comment by HouseBreaker** [comment]
yes

**Comment by rpalmon** [comment]
I wonder if there is a site where we could put our NNID information and upload a ticket so that when we go back to the eShop we could install the game of the ticket.

**Comment by HouseBreaker** [comment]
Tickets have very little to do with your nnid and also a site like that would be impossible since all that account data is on Nintendo's servers.

Anyway I'm closing this issue because it has nothing to do with Shameless
