### ISSUE TITLE
Question: About showing the sizes

### ISSUE THREAD

**Issue by KarmicBacklash** [HouseBreaker/Shameless#2]
Is there a specific reason that the sizes are not listed with the rest of the info on the list?

Is there a restriction that stops you from having this or is it personal preference?

**Comment by HouseBreaker** [comment]
Yes, the reason is that getting the size means asking the CDN for info on how big the title is. This either takes a couple seconds for titles or can take up to several minutes. So you can imagine how long it would take to get the sizes of 1500 titles.

That's why I made it optional.

**Comment by KarmicBacklash** [comment]
I don't mean to press this further, but would it be possible to fetch the info, have that info transcribed to a .txt and in the future have it access the info from the txt so it wouldn't have to get it from the CDN?

I have no idea if that made sense...

**Comment by HouseBreaker** [comment]
If you want I can make a program which asks the CDN for the size info on all the titles, uploads it somewhere and then have Shameless retrieve it. 

It would take a long time to retrieve the title size for every title in the nfshost database but you've just given me another project lmao

**Comment by KarmicBacklash** [comment]
Yay?

**Comment by HouseBreaker** [comment]
Shameless 1.8 now shows title sizes next to the titles.
