### ISSUE TITLE
The new site is 3ds.titlekeys.gq

### ISSUE THREAD

**Issue by LennyMcLennington** [HouseBreaker/Shameless#24]
so you will need to change the code slightly, its not working just gives an error

**Comment by Astilex5** [comment]
I can also confirm that the domain was changed to [http://3ds.titlekeys.gq/](

Thread : [https://www.)reddit.com/r/3dspiracy/comments/6a63r1/3dstitlekeys_has_moved_to_new_domain/](url)

**Comment by HouseBreaker** [comment]
fixed in latest update
