### ISSUE TITLE
qr code failed to download

### ISSUE THREAD

**Issue by timelord217** [HouseBreaker/Shameless#4]
On my New 3ds, I'm using the latest versions of both FBI and Shameless and it won't download any qr codes. It works just fine on my other 3ds, just not my primary. Help please?

**Comment by HouseBreaker** [comment]
It might be the database moving hosts today. I updated Shameless to reflect the change. Give it a try and report back if you're still having issues.

**Comment by HouseBreaker** [comment]
Check if it works with you with Shameless 1.8.6. There was a bug where https links were being made instead of http.

**Comment by BEN3856** [comment]
I'm encountering a similar problem. I scan the QR code with my 3ds on the eshop, right? Well, it says the QR code is not supported. Please, help

**Comment by timelord217** [comment]
Have you updated to the latest? Mine has been fixed for a while

**Comment by BEN3856** [comment]
1.8.7 is the latest version, right?

**Comment by timelord217** [comment]
Yes, but if you have any problems, just get them another way. There's apps you can add on your 3ds now, that act like shameless, I'd recommend the Freeshop, or Ciangel. I have both because why not.

**Comment by BEN3856** [comment]
Where can i get them? and are they free?

**Comment by timelord217** [comment]
They are free https://gbatemp.net/threads/wip-freeshop-open-source-eshop-clone.426573/

https://gbatemp.net/threads/release-ciangel-download-good-cias-right-on-your-3ds.423326/

Follow the instructions, because you do need to get a file from https://3ds.titlekeys.com for free shop. I use freeshop more, but use both

**Comment by timelord217** [comment]
And honestly, Freeshop and Ciangel are basically the same, but one has a better look and one is updated often

**Comment by BEN3856** [comment]
I'm sorry, but i'm a bit lost. So, i've downloaded the cia file for Freeshop, all i have to do now is move it to my 3ds and import it, right? but i don't understand the tutorial and what is the file i need to get?

**Comment by timelord217** [comment]
Make a folder named Freeshop or something on the root of your SD card and put enctitlekeys.bin from   https://3ds.titlekeys.com into it, and install the cia

**Comment by BEN3856** [comment]
Ok, so the app works. But, is there a way i can get dlc for free using Freeshop? i've been dying to get all the Super Smash Bros DLC

**Comment by timelord217** [comment]
Sort of... Use https://3ds.titlekeys.com to find it and scan it using fbi, also make sure FBI is up to date

**Comment by timelord217** [comment]
Also, I wouldn't recommend ever using the eshop again, or it will delete your dlc each time upon entering the eshop, making it to where you have to reinstall it

**Comment by BEN3856** [comment]
Wait, is FBI another thing i have to get that's not already in every 3ds?

**Comment by timelord217** [comment]
https://github.com/Steveice10/FBI/releases

You want to get the latest .CIA and install it.

**Comment by timelord217** [comment]
It makes scanning qr codes for downloading games easier too.

**Comment by timelord217** [comment]
From the computer or any screen you can display it on

**Comment by HouseBreaker** [comment]
yes that is exactly what Shameless is for. for installing tickets by scanning their QR codes with FBI.

**Comment by timelord217** [comment]
Yep

**Comment by BEN3856** [comment]
No wonder why it never worked for me. I scanned the code through the eshop

**Comment by BEN3856** [comment]
Oh, thank you so much. I just can't express how happy i got after getting all the dlc's. I couldn't help but squel

**Comment by timelord217** [comment]
Lol,have fun with your power

**Comment by BEN3856** [comment]
Thanks. Do you have any advices, though? so i don't possibly get caught.

**Comment by timelord217** [comment]
You won't get caught. Your 3ds is already beyond it's warranty. Don't worry

**Comment by HouseBreaker** [comment]
it's incredibly easy to get caught with illegal tickets. Nintendo is just not doing anything about it at this point. as soon as they implement a small (even server-side) system to ban people with invalid tickets, that's it.

**Comment by timelord217** [comment]
Oh. Then never mind. Listen to the professional

**Comment by BEN3856** [comment]
So, basically if Nintendo finally decides to give a s**t, we're screwed?

**Comment by HouseBreaker** [comment]
you two look like you resolved your issues so I'll close this. have a good day.
