### ISSUE TITLE
Binding of Isaac

### ISSUE THREAD

**Issue by CrossBowKill** [HouseBreaker/Shameless#5]
Dont know where to ask (reddit is not allowed because it is piracy after all), so I try my luck here. I tried to dl The binding of isaac and the ticket worked and the download went through with no problem but the game does not load after the "nintendo 3ds" screen.

As I said not a real issue with your program/commit (it works like a charm) maybe you can help me

P.S using a new 3ds so it should work on that perspective

**Comment by HouseBreaker** [comment]
If it's a relatively new game it probably uses seed crypto. It'll install but will hang on the red 3ds screen. 

As such, either visiting the eShop page of a title which has this problem or repairing the game from the eShop will fix this issue.

Try it and report back.

**Comment by CrossBowKill** [comment]
Oh totally forgot about that, even though I needed it like 2 weeks ago for the old Pokemon editions too.

Thanks for your help
