### ISSUE TITLE
Still not working.

### ISSUE THREAD

**Issue by timelord217** [HouseBreaker/Shameless#6]
It says:
Failed to install from qr code.
(link)
Result code: 0xD8E08019
Level: Permanant (27)
Summary: invalid argument (7)
Module: AM (31)
Desc: <unknown> 25

**Comment by HouseBreaker** [comment]
Tell me which titleID so I can test it.

**Comment by timelord217** [comment]
00040000000C6400
But the thing is, it works just fine on my older 3ds

**Comment by timelord217** [comment]
I just tried it on the USA Mario And Luigi Dream team and it works fine on the N3DS

**Comment by HouseBreaker** [comment]
I only have an old 3ds so I can't really test it for new 3ds. Does only installing the ticket w/o downloading from CDN work?

**Comment by timelord217** [comment]
It doesn't download the ticket

**Comment by HouseBreaker** [comment]
Try to put the ticket on the SD card and install it from there. Does that work?

**Comment by timelord217** [comment]
how would I do that?

**Comment by HouseBreaker** [comment]
Generate all tickets, then find the one you've been trying. Transfer it to your 3ds' SD card and try to install it with FBI.

**Comment by timelord217** [comment]
how would I transfer it? How would I download the ticket?

**Comment by timelord217** [comment]
nevermind, I figured it out. I'll give it a go

**Comment by timelord217** [comment]
Is there a specific folder I'm supposed to put the ticket in?

**Comment by HouseBreaker** [comment]
No, FBI can install tickets from any folder on the SD card.

**Comment by timelord217** [comment]
alright

**Comment by timelord217** [comment]
Ok, it seems to be working now. Thanks man, great work on shameless, you're legend

**Comment by HouseBreaker** [comment]
Glad it works!
