### ISSUE TITLE
Response code 302

### ISSUE THREAD

**Issue by Anunnymous** [HouseBreaker/Shameless#7]
I keep getting

"Failed to install from QR code.
https://hec.su/XXXX
HTTP server returned response code 302"

On any tik I try to grab.

1.8.5 on Old 3DS

Thanks.

**Comment by HouseBreaker** [comment]
It works absolutely fine here, just tried to generate a qr code and install a title. Mind sharing any link you had issues with?

**Comment by Anunnymous** [comment]
/dF7F 

That's the one I was trying most recently but my 3DS doesn't seem to want to download any of them from redirects. I can download on my PC from that URL just fine and install the tik manually with FBI just fine.  My 3DS just won't download redirects for some reason.

**Comment by HouseBreaker** [comment]
Which FBI version are you running?

I know there was a specific version of it which rolled out a fix for redirection.

**Comment by Anunnymous** [comment]
Ah, that was it. I was still running 2.1.1.  Sorry for wasting your time but the help is much appreciated.

**Comment by HouseBreaker** [comment]
No problem!
