### ISSUE TITLE
Qr Failed to download

### ISSUE THREAD

**Issue by juice3041** [HouseBreaker/Shameless#8]
Everytime i try to download anything a error that pops up, i am on the latest version plus the latest version of FBI. the error is eg.

Failed to install from QR code.
https://hec.su/dgrr 
Result code : 0xD8A0A03C
Level: Permanent (27)
Summary: Invalid state (5)
Module: HTTP (40)
Desc: Failed to verify TLS certificate (60)

**Comment by HouseBreaker** [comment]
Well, first off, that's a link to some video. Not a ticket.

**Comment by juice3041** [comment]
the qr that that link is for  was for the Hyrule Warriors Legend US update

**Comment by juice3041** [comment]
its supposed to be https://hec.su/dGrr i forgot to capitalize the g

**Comment by HouseBreaker** [comment]
I was able to reproduce this and I have a pretty good idea of what's causing it.

Sometimes hec.su returns a https url which FBI freaks out over and aborts the installation.

The thing is, if I remove the "s" from https and make a QR code out of that, FBI installs the title just fine.

Thank you for discovering this, fix coming soon.

**Comment by juice3041** [comment]
Thanks will wait for fix

**Comment by HouseBreaker** [comment]
https://github.com/HouseBreaker/Shameless/releases/tag/1.8.6

**Comment by HouseBreaker** [comment]
Let me know if this fixes your issue.

**Comment by juice3041** [comment]
Yes it works now, thanks
