### ISSUE TITLE
Exception when trying to generate a QR code

### ISSUE THREAD

**Issue by eugeneromero** [HouseBreaker/Shameless#9]
The latest version, 1.8.6, throws an exception every time I try to generate a QR code. The error is pasted below. Version 1.8.5 worked fined (although of course the https QR codes didn't work for FBI).

This is on a Windows 10 machine, with .NET 4.6.1.

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   in Newtonsoft.Json.JsonTextReader.ParseValue()
   in Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   in Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   in Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   in Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   in Shameless.QRGeneration.QrUtils.Shorten(String url)
   in System.Threading.Tasks.Task`1.InnerInvoke()
   in System.Threading.Tasks.Task.Execute()
```

**Comment by HouseBreaker** [comment]
Which title did you try? I need it to try and reproduce it.

**Comment by eugeneromero** [comment]
I was getting the error with any title. However, I started looking into the error a bit myself and came to realize that the problem was related to my Internet connection sending traffic in some weird way. Testing with a different network solved the issue. So this was not a problem with the application at all. I will now close this ticket.
Thanks for getting back to me regardless!
